-- Role: "Kasey"
-- DROP ROLE IF EXISTS "Kasey";

CREATE ROLE "Kasey" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:ZbXAttpc6U9gxJAE7E3jBg==$zugjRqaMSHr2djuxcy7I7XvYyX6imFKQQGNQEL2ptTU=:YhoodREcEFa0d+tuLQ4akjQwlUEHukViFVxR/A3oiwU=';